//! Club news, from mlb.com's own RSS feeds.
//!
//! # Why RSS and not the Stats API
//!
//! The Stats API is a statistics service: it publishes schedules, lines and media, and
//! nothing that reads like a news story. MLB's editorial output is published as RSS
//! instead, one feed per club at `mlb.com/{slug}/feeds/news/rss.xml`, and that is the
//! only keyless source of it. It goes through the Rust side like every other external
//! request -- the webview still makes no network calls of its own.
//!
//! # The slug
//!
//! mlb.com addresses a club by its own short name, lowercased with every non-alphanumeric
//! character removed. That rule was checked against all thirty clubs and holds for every
//! one of them, including the awkward ones: "D-backs" is `dbacks`, "Red Sox" is `redsox`,
//! "Blue Jays" is `bluejays`. It is derived rather than hard-coded so a relocation or a
//! rename does not need a code change -- `teamName` comes from the API.
//!
//! # The parser
//!
//! Deliberately small and hand-written rather than a general XML dependency. The feed is
//! machine-generated by one publisher with a fixed shape, and everything read from it is
//! rendered as text, never as markup, so the failure mode of a malformed feed is a
//! missing field rather than anything worse. `parse_rss` is pure and covered by tests
//! against a real captured item.

use tauri::{AppHandle, State};

use super::AppState;
use crate::error::Result;
use crate::mlb::{self, models::NewsItem};
use crate::storage::config;

/// Articles about the followed club, newest first.
///
/// With no club followed and none passed, MLB's league-wide feed is returned instead of
/// an error: an empty news panel that explains nothing is worse than league news.
#[tauri::command]
pub async fn get_team_news(
    app: AppHandle,
    state: State<'_, AppState>,
    team_id: Option<u32>,
    limit: Option<usize>,
) -> Result<Vec<NewsItem>> {
    let team_id = team_id.or(config::load(&app)?.favorite_team());

    let slug = match team_id {
        Some(id) => {
            let team = mlb::fetch_team(&state.client, id).await?;
            team.team_name
                .or(team.club_name)
                .or(team.name)
                .as_deref()
                .map(team_slug)
        }
        None => None,
    };

    let xml = mlb::fetch_news_feed(&state.client, slug.as_deref()).await?;
    let mut items = parse_rss(&xml);
    items.truncate(limit.unwrap_or(20).min(50));
    Ok(items)
}

/// mlb.com's path segment for a club name: lowercase, alphanumerics only.
///
/// "D-backs" -> `dbacks`, "Red Sox" -> `redsox`, "Blue Jays" -> `bluejays`.
pub fn team_slug(team_name: &str) -> String {
    team_name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .flat_map(|c| c.to_lowercase())
        .collect()
}

/// Every `<item>` in an RSS document, in feed order (mlb.com publishes newest first).
pub fn parse_rss(xml: &str) -> Vec<NewsItem> {
    let mut out = Vec::new();

    for chunk in xml.split("<item>").skip(1) {
        // Stop at the item's own close so a malformed feed cannot bleed one article's
        // fields into the next one's.
        let item = chunk.split("</item>").next().unwrap_or(chunk);

        let Some(title) = tag_text(item, "title") else {
            continue;
        };
        let Some(link) = tag_text(item, "link") else {
            continue;
        };

        out.push(NewsItem {
            title,
            link,
            published: tag_text(item, "pubDate").and_then(|d| to_rfc3339(&d)),
            author: tag_text(item, "dc:creator"),
            image: attribute(item, "<image ", "href"),
            // MLB puts the standfirst in `description` on some feeds and omits it on
            // others; an absent one just renders as a headline with no body.
            summary: tag_text(item, "description").filter(|s| !s.is_empty()),
        });
    }

    out
}

/// The text of the first `<name>...</name>`, unwrapped from CDATA and unescaped.
fn tag_text(item: &str, name: &str) -> Option<String> {
    let open = format!("<{name}>");
    let close = format!("</{name}>");
    let start = item.find(&open)? + open.len();
    let end = item[start..].find(&close)? + start;
    let raw = item[start..end].trim();

    let inner = raw
        .strip_prefix("<![CDATA[")
        .and_then(|r| r.strip_suffix("]]>"))
        .unwrap_or(raw);

    Some(unescape(inner.trim()))
}

/// The value of one attribute on the first tag starting with `open`.
fn attribute(item: &str, open: &str, attr: &str) -> Option<String> {
    let at = item.find(open)? + open.len();
    let tag = &item[at..item[at..].find('>')? + at];
    let key = format!("{attr}=\"");
    let start = tag.find(&key)? + key.len();
    let end = tag[start..].find('"')? + start;
    Some(unescape(&tag[start..end]))
}

/// The five XML entities, plus the numeric forms mlb.com actually emits.
///
/// `&#x3D;` for `=` is the one that matters in practice -- it appears inside media URLs
/// and turns a working link into a 404 if it is left encoded. The same escaping bites
/// the Savant clip scraper, for the same reason.
fn unescape(s: &str) -> String {
    s.replace("&#x3D;", "=")
        .replace("&#39;", "'")
        .replace("&apos;", "'")
        .replace("&quot;", "\"")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        // Ampersand last: doing it first would re-decode the entities above.
        .replace("&amp;", "&")
}

/// "Wed, 09 Sep 2026 06:42:00 GMT" -> RFC 3339, which is what the frontend parses.
///
/// A date that will not parse is dropped rather than passed through: the UI formats it
/// with `Date`, and an unparseable string renders as "Invalid Date".
fn to_rfc3339(raw: &str) -> Option<String> {
    chrono::DateTime::parse_from_rfc2822(raw)
        .ok()
        .map(|d| d.to_rfc3339())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// One real item, captured from the Dodgers feed.
    const ITEM: &str = r#"<rss><channel><item><title><![CDATA[Skubal's longest Dodger start fuels LA's 6th straight win]]></title><link>https://www.mlb.com/dodgers/news/tarik-skubal-starts-for-dodgers-vs-reds-on-sept-8</link><guid isPermaLink="false">x</guid><pubDate>Wed, 09 Sep 2026 06:42:00 GMT</pubDate><dc:creator>Sonja Chen</dc:creator><mlb:team id="119" teamcode="lan"/><image href="https://img.mlbstatic.com/mlb-images/image/upload/t_16x9/v1/mlb/hfev3cjpndkr6ro6sg7q"/></item></channel></rss>"#;

    #[test]
    fn every_club_slug_matches_mlb_coms_own() {
        // The awkward ones. Checked against live 200/404 responses for all thirty.
        assert_eq!(team_slug("D-backs"), "dbacks");
        assert_eq!(team_slug("Red Sox"), "redsox");
        assert_eq!(team_slug("White Sox"), "whitesox");
        assert_eq!(team_slug("Blue Jays"), "bluejays");
        assert_eq!(team_slug("Athletics"), "athletics");
        assert_eq!(team_slug("Dodgers"), "dodgers");
    }

    #[test]
    fn an_item_is_read_whole() {
        let items = parse_rss(ITEM);
        assert_eq!(items.len(), 1);
        let item = &items[0];
        assert!(item.title.starts_with("Skubal's longest"));
        assert!(item.link.ends_with("sept-8"));
        assert_eq!(item.author.as_deref(), Some("Sonja Chen"));
        assert!(item.image.as_deref().unwrap().starts_with("https://img.mlbstatic.com/"));
        assert_eq!(item.published.as_deref(), Some("2026-09-09T06:42:00+00:00"));
    }

    #[test]
    fn cdata_is_unwrapped_and_entities_decoded() {
        let xml = r#"<item><title><![CDATA[Reds &amp; Dodgers]]></title><link>https://x/a?b&#x3D;1</link></item>"#;
        let items = parse_rss(xml);
        assert_eq!(items[0].title, "Reds & Dodgers");
        // The `=` padding trap: left encoded, this link 404s.
        assert_eq!(items[0].link, "https://x/a?b=1");
    }

    #[test]
    fn one_items_fields_never_bleed_into_the_next() {
        let xml = r#"<item><title>First</title><link>https://a</link><dc:creator>Ann</dc:creator></item><item><title>Second</title><link>https://b</link></item>"#;
        let items = parse_rss(xml);
        assert_eq!(items.len(), 2);
        assert_eq!(items[1].title, "Second");
        // Without the `</item>` cut this would inherit "Ann" from the item before it.
        assert_eq!(items[1].author, None);
    }

    #[test]
    fn an_item_with_no_link_is_skipped_rather_than_rendered_dead() {
        let xml = r#"<item><title>Headline only</title></item>"#;
        assert!(parse_rss(xml).is_empty());
    }

    #[test]
    fn an_unparseable_date_is_dropped_not_passed_through() {
        assert_eq!(to_rfc3339("not a date"), None);
        assert!(to_rfc3339("Wed, 09 Sep 2026 06:42:00 GMT").is_some());
    }
}
